foo: foo version 10002
spring: 
   datasource:
        name: test
        url: jdbc:mysql://192.168.2.235:5630/devops-bussiness?useUnicode=true&characterEncoding=utf8
        username: root
        password: CCpg@2017
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 4
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis: 
    basepackage: com.lovnx.web.mapper
    xmlLocation: classpath:mapper/**/*.xml
    
        
        

